FROM openjdk:11
MAINTAINER appgate.com
RUN addgroup -S appgate && adduser -S appgate -G appgate
USER appgate:appgate
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} operation-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/operation-0.0.1-SNAPSHOT.jar"]